# Generated by Django 3.1.12 on 2025-01-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20250120_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
