# Generated by Django 3.1.12 on 2025-01-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20250120_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='date',
            field=models.DateField(auto_now_add=True, default='2025-01-23'),
            preserve_default=False,
        ),
    ]
